[build]
  command = "npm run build"
  publish = "dist/browser"

[dev]
  command = "npm run dev:ssr"
  framework = "#netlify-angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200